/* table is pizza_sales*/
SELECT * FROM pizza_sales

/*for total revenue we should sum total_price:-817860.05083847*/
SELECT SUM(total_price) AS Revenue FROM pizza_sales

/* FOR AVG ORDERS WE NEED TO DIVIDE IT BY REVENUE/ TOTAL NUMBER OF ORDERS AS ORDERS HAVE DUPLICATE ORDER_ID WE NEED TO USE 
DISTINCT :- 38.30 */
SELECT SUM(total_price)/COUNT(DISTINCT order_id) as AVG_ORDERS FROM pizza_sales

/* Total pizza sold it can be done by SUM of QUANTITY :49574 */
SELECT SUM(quantity) AS TOTAL_PIZZA_SOLD FROM pizza_sales

/*TOTAL ORDERS :DISTINCT COUNT OF ORDER ID WILL GIVE YOU TOTAL ORDERS :21350 */
SELECT COUNT(DISTINCT order_id) AS TOTAL_ORDERS FROM pizza_sales

/* AVG PIZZA ORDERS :DIVIDE TOTAL_PIZZA_SOLD BY TOTAL_ORDERS :2
AS HERE 2 IS SHOWN WE NEED TO CAST THE VALUES INTO DECIMAL */
SELECT CAST (CAST (SUM(quantity) AS DECIMAL (10,2))/
CAST (COUNT(DISTINCT order_id) AS DECIMAL (10,2)) AS DECIMAL(10,2)) AS AVG_PIZZA_ORDERS
 FROM pizza_sales

 /*TRENDS FOR WEEKDAYS AND WEEKENDS WE CAN FIND IT USING ORDER DATE AND TOTAL ORDER
 DW IS DATE OF THE WEEK ,ORDER_DATE TO STRING 
 MAXIMUM ON FRIDAY :- 3538 ,MINIMUM ON SUNDAY:-2624*/
 SELECT DATENAME(DW,order_date) AS ORDER_DAY ,COUNT(DISTINCT order_id) AS TOTAL_ORDER
 FROM Pizza_sales
 GROUP BY  DATENAME(DW,order_date)
 ORDER BY TOTAL_ORDER DESC

 /* TREND FOR THE MONTH
 JULY HAS HIGHEST SALES :1935, OCTOBER HAS LOWEST SALES :1646*/
 SELECT DATENAME(MONTH,order_date) AS ORDER_MONTH ,COUNT(DISTINCT order_id) AS TOTAL_ORDER
 FROM Pizza_sales
 GROUP BY  DATENAME(MONTH,order_date)
 ORDER BY TOTAL_ORDER DESC

 /*TREND BY HOURS*/
 SELECT DATEPART(HOUR,order_time) AS ORDER_HOUR ,COUNT(DISTINCT order_id) AS TOTAL_ORDER
 FROM Pizza_sales
 GROUP BY  DATEPART(HOUR,order_time)
 ORDER BY TOTAL_ORDER DESC

 /*PERCENTAGE OF SALES BY PIZZA CATEGORY
 CLASSIC HAS MAXIMUM SALES AND VEGGIE HAS MINIMUM SALES*/
 SELECT pizza_category ,SUM(total_price)AS TOTAL_SALES,SUM(total_price)*100/
 (SELECT SUM(total_price) FROM pizza_sales) AS PCT_TOTAL_SALES
 FROM pizza_sales
 GROUP BY pizza_category
 ORDER BY SUM(total_price) DESC

 /*FILTER BY MONTH*/
 SELECT pizza_category ,SUM(total_price)AS TOTAL_SALES,SUM(total_price)*100/
 (SELECT SUM(total_price) FROM pizza_sales WHERE MONTH(order_date)=1) AS PCT_TOTAL_SALES
 FROM pizza_sales
 WHERE MONTH(order_date)=1
 GROUP BY pizza_category
 ORDER BY SUM(total_price) DESC
 
 /*FILTER BY QUARTER*/
  SELECT  pizza_category ,SUM(total_price)AS TOTAL_SALES,SUM(total_price)*100/
 (SELECT SUM(total_price) FROM pizza_sales  WHERE DATEPART(QUARTER,order_date)=1) AS PCT_TOTAL_SALES
 FROM pizza_sales
 WHERE DATEPART(QUARTER,order_date)=1
 GROUP BY pizza_category
 ORDER BY SUM(total_price) DESC

 /*PERCENTAGE OF SALES BY PIZZA_SIZE
 LARGE HAS MAXIMUM SALES AND XXL HAS LOWEST SALES */
 SELECT pizza_size ,CAST(SUM(total_price) AS DECIMAL(10,2))AS TOTAL_SALES,CAST(SUM(total_price)*100/
 (SELECT SUM(total_price) FROM pizza_sales) AS DECIMAL(10,2)) AS PCT_TOTAL_SALES
 FROM pizza_sales
 GROUP BY pizza_size
 ORDER BY SUM(total_price) DESC

 /*FOR QUARTER*/
 SELECT pizza_size ,CAST(SUM(total_price) AS DECIMAL(10,2))AS TOTAL_SALES,CAST(SUM(total_price)*100/
 (SELECT SUM(total_price) FROM pizza_sales) AS DECIMAL(10,2)) AS PCT_TOTAL_SALES
 FROM pizza_sales
 WHERE DATEPART(QUARTER,order_date)=1
 GROUP BY pizza_size
 ORDER BY SUM(total_price) DESC


 /*TOP FIVE BEST SELLER PIZZA*/
 SELECT TOP 5 pizza_name,SUM(total_price) AS TOTAL_REVENUE
 FROM pizza_sales
 GROUP BY pizza_name
 ORDER BY TOTAL_REVENUE DESC 

 /*BOTTOM FIVE PIZZA */
 SELECT TOP 5 pizza_name,SUM(total_price) AS TOTAL_REVENUE
 FROM pizza_sales
 GROUP BY pizza_name
 ORDER BY TOTAL_REVENUE ASC

 /*TOP 5 BY QUANTITY*/
 SELECT TOP 5 pizza_name,SUM(quantity) AS TOTAL_QUANTITY
 FROM pizza_sales
 GROUP BY pizza_name
 ORDER BY TOTAL_QUANTITY DESC

 /*BOTTOM 5 BY QUANTITY*/
 SELECT TOP 5 pizza_name,SUM(quantity) AS TOTAL_QUANTITY
 FROM pizza_sales
 GROUP BY pizza_name
 ORDER BY TOTAL_QUANTITY ASC

 /* TOP 5 BY TOTAL_ORDERS*/
 SELECT TOP 5 pizza_name,COUNT(DISTINCT order_id)AS TOTAL_ORDERS
 FROM pizza_sales
 GROUP BY pizza_name
 ORDER BY TOTAL_ORDERS DESC

 /*BOTTOM 5 BY TOTAL ORDERS*/
 SELECT TOP 5 pizza_name,COUNT(DISTINCT order_id)AS TOTAL_ORDERS
 FROM pizza_sales
 GROUP BY pizza_name
 ORDER BY TOTAL_ORDERS ASC

